### PR TITLE
Flatten log fields and remove circular references

### LINKED ISSUE #5: Prevent Circular Structure error for slack service
Slack will use `JSON.stringify(value)` to handle non-string `value`,
so it would throw Circular Structure error when `value` having circular reference.
https://github.com/slackapi/node-slack-sdk/blob/fb4bc6fe62e055581d342b8279350d59325930d3/lib/clients/helpers.js#L30

It throws exception when passing `request` object from router of Express
https://github.com/17media/node-logger/blob/c583a30e5471895b87c0b4934e4fa426f6c4693c/src/service/slack.js#L41

We can avoid it by passing value to a filter function likes:
```
import { forEach, isObject } from 'lodash';

function removeCircularStructure(object, set = new Set(), nextObject = {}) {
  forEach(object, (value, key) => {
    if (isObject(value)) {
      if (set.has(value)) {
        return;
      }

      set.add(value);
      nextObject[key] = removeCircularStructure(value, set);
      return;
    }

    nextObject[key] = value;
  });

  return nextObject;
}
```

Or do something else to prevent this error.

### PR DESCRIPTION
**Pull request by boczeratul**
this fixes #5 

1. Add util to flatten log fields and remove circular references
2. Add corresponding unit tests

### CODE REVIEW

File: src/utils/index.js [hunk 1]
```diff
@@ -10,7 +14,35 @@ const hasAllKeys = (testObject, keys) => {
...
+  // if type or source is primitive, return value directly
+  if (!isObject(source)) {
+    const result = {};
+    result[prefix || 'value'] = source;
+    return result;
+  }
+
+  // check for circular reference
+  if (refSet.has(source)) {
+    return {};
```
Comment (eason17) [inline src/utils/index.js]: How about returning a special string or something instead of `{}` to tell it encounters a circular reference

File: src/utils/index.js [hunk 2]
```diff
@@ -10,7 +10,35 @@ const hasAllKeys = (testObject, keys) => {
 
 const formatLogLevel = logLevel => ['debug', 'info', 'warn', 'error'][logLevel];
 
+const flattenObject = (source, prefix = '', refSet = new Set()) => {
+  // if type or source is primitive, return value directly
+  if (!isObject(source)) {
+    const result = {};
+    result[prefix || 'value'] = source;
+    return result;
```
Comment (eason17) [inline src/utils/index.js]: Can be ES6 syntax
`return { [prefix || 'value']: source };`
